spring:
  profiles:
    active: dev # 表示开发环境
    #active: test # 表示测试环境
    #active: prop 表示生产环境

  #网关规则 前端访问localhost:88?keyWord=qq的时候跳转到 https://www.baidu.com/，访问qq的时候跳转到 https://im.qq.com/index
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com/
          predicates:
            - Query=keyWord, baidu

        - id: qq_route
          uri: https://im.qq.com/index
          predicates:
              - Query=keyWord, qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            #前端项目带api的都来到网关
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: renren_route
          uri: lb://renren-fast
          predicates:
            #前端项目带api的都来到网关
              - Path=/api/**
          filters:
             #路径重写 localhost:88/api/captcha.jpg 重写成 localhost:8080/renren-fast/captcha.jpg
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
            #商品服务路由

